apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ray-cluster
  namespace: ray
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: ray
  project: default
  source:
    path: ray_cluster
    repoURL: https://github.com/milesjwinter/argocd-fun.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
