apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    chart: argo-workflows
    helm:
      values: |
        pushgateway:
          enabled: false
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 0.2.4
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
